Vagrant.configure(2) do |config|
config.vm.define "database" do |database|
  database.vm.box = "ubuntu/xenial64"
  database.vm.hostname = "Database"
  database.vm.network "private_network", ip: "192.168.55.54"
  database.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
  database.vm.provision "shell", path: "SH/db.sh"
  end

config.vm.define "webserver" do |webserver|
  webserver.vm.box = "ubuntu/xenial64"
  webserver.vm.hostname = "Webserver"
  webserver.vm.network "private_network", ip: "192.168.55.55"
  webserver.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  webserver.vm.provider "virtualbox" do |vb|
    vb.memory = "512"  
  end
  webserver.vm.synced_folder ".", "/var/www/html"  
  webserver.vm.provision "shell", path: "SH/web.sh"
  # Packages vom lokalen Server holen
  # sudo sed -i -e"1i deb {{webserver.server}}/apt-mirror/mirror/archive.ubuntu.com/ubuntu xenial main restricted" /etc/apt/sources.list 
  end

end